### ISSUE TITLE
A few tips

### ISSUE THREAD

**Issue by TeTpaAka** [minetest-mods/myholeinthewall#1]
https://github.com/DonBatman/myholeinthewall/blob/master/machine.lua#L388-L646
Use if elseif or make a list and loop through it. They all do the same.

https://github.com/DonBatman/myholeinthewall/blob/master/machine.lua#L648
make_ok should probably only have values of "0" and "1". Consider using true and false instead. Then you can simply check if make_ok then ... end. (I think this is possible now, too, but I'm not too sure.)

And as always: Indentation makes everything more readable.

**Comment by DonBatman** [comment]
I see you have been looking through my mods again. I can't tell you how
much I appreciate it. I have learned a lot from your comments.
I am out of town for a family problem. I will update the mods as soon as I
can.
Again, thank you very much.
